kind: Pod
apiVersion: v1
metadata:
  name: web1
spec:
  containers:
    - name: c00
      image: httpd
      ports:
       - containerPort: 80
	   
	   
kind: Pod
apiVersion: v1
metadata:
  name: web2
spec:
  containers:
    - name: c00
      image: nginx
      ports:
       - containerPort: 80	  