kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: Demopod
  annotations:
    description: Annotations for testing
spec:                                    
  containers:                      
    - name: Cont-1                     
      image: ubuntu              
      command: ["/bin/bash", "-c", "while true; do echo Hello-Akshay; sleep 5 ; done"]
  restartPolicy: Never         # Defaults to Always